name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to publish"
        required: true
      tag:
        description: "Tag"
        required: true
        default: "latest"
        type: choice
        options:
          - latest
          - snapshot
          - next

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
      - run: yarn install --immutable --mode=skip-build

      - name: "@apollo/client-react-streaming: update version"
        run: |
          yarn workspace @apollo/client-react-streaming exec npm pkg set "version=${{ inputs.version }}"
          yarn workspace @apollo/client-react-streaming exec jq '{ version: .version, dependencies: .dependencies, peerDependencies: .peerDependencies }' package.json

      - name: "@apollo/client-react-streaming: publish"
        run: yarn workspace @apollo/client-react-streaming exec npm publish --access public --tag ${{ inputs.tag }} --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "@apollo/experimental-nextjs-app-support: update version and dependencies"
        run: |
          yarn workspace @apollo/experimental-nextjs-app-support exec npm pkg set "dependencies[@apollo/client-react-streaming]=${{ inputs.version }}" "version=${{ inputs.version }}"
          yarn workspace @apollo/experimental-nextjs-app-support exec jq '{ version: .version, dependencies: .dependencies, peerDependencies: .peerDependencies }' package.json

      - name: "@apollo/experimental-nextjs-app-support: publish"
        run: yarn workspace @apollo/experimental-nextjs-app-support exec npm publish --access public --tag ${{ inputs.tag }} --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
